language: node_js
node_js:
  - lts/*

env:
 global:
   - GITHUB_REPO: github.com/wuruofan/wuruofan.github.io.git

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g

install:
  - npm install
  - npm install --save hexo-theme-fluid
  - cp resources/img/default.png node_modules/hexo-theme-fluid/source/img/
  - cp resources/img/icon.png node_modules/hexo-theme-fluid/source/img/

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wuruofan"
  - git config user.email "demonsimon@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GITHUB_ACCESS_TOKEN}@${GITHUB_REPO}" master:master

branches:
  only:
    - source
